version: "3.3"

services:
  kong:
    image: kong:latest
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
    environment:
      KONG_DATABASE: ${KONG_DATABASE_TYPE}
      KONG_PG_HOST: ${KONG_DATABASE_HOST}
      KONG_CASSANDRA_CONTACT_POINTS: ${KONG_DATABASE_HOST}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    deploy:
      mode: global
      endpoint_mode: ${ENDPOINT_MODE}
      restart_policy:
        condition: on_failure

  konga:
    image: pantsel/konga:latest
    depends_on:
      - kong
    ports:
      - "1337:1337"
    environment:
      DB_ADAPTER: ${KONGA_DB_ADAPTER}
      DB_HOST: ${KONGA_DB_HOST}
      DB_PORT: ${KONGA_DB_PORT}
      DB_USER: ${KONGA_DB_USER}
      DB_PASSWORD: ${KONGA_DB_PASSWORD}
      DB_DATABASE: ${KONGA_DB_DATABASE}
      NODE_ENV: ${KONGA_NODE_ENV}
    network_mode: host

  kong-migration:
    image: kong:latest
    environment:
      KONG_DATABASE: ${KONG_DATABASE_TYPE}
      KONG_PG_HOST: ${KONG_DATABASE_HOST}
      KONG_CASSANDRA_CONTACT_POINTS: ${KONG_DATABASE_HOST}
    command: kong migrations up
